name: Building GSI..

on: push
    
env:
  ROM_URL: https://download1339.mediafire.com/il8t1p4vdvzg/hmj6vgpvxiyf52x/lenovo_k10_plus%28l39051%29_kama2_ROW_B229_04122019_SIGN_RepairMyMobile.in.zip
  ROM_NAME: ZUI
  TZ: Europe/London
  MIR: cow
  TYPE: ab
  DEVICE: channel
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/00p513-dev/ErfanGSIs-VelanGSIs.git  ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --$TYPE
             
       - name: Upload Image
         uses: actions/upload-artifact@v2
         with:
          name: Image
          path: "ErfanGSIs/output/*.img"
          
          
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*.txt
