name: Building GSI..

on: push
    
env:
  ROM_URL: https://versaweb.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/MIUI-WEEKLY-RELEASES/21.2.24/xiaomi.eu_multi_HMNote7_21.2.24_v12-10.zip
  ROM_NAME: MIUI
  TZ: Europe/London
  MIR: cow
  ZIP_NAME: xiaomi.eu
  TYPE: ab
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/00p513-dev/ErfanGSIs-channel.git  ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --$TYPE
       
       - name: ZIP 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              xz -9 ErfanGSIs/output/*.img
 
             
       - name: Upload Image
         uses: actions/upload-artifact@v2
         with:
          name: Image
          path: "ErfanGSIs/output/*.img.xz"
          
          
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*.txt
